// apps/react-demo/src/App.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react'

import {
  MpegtsPlayer as MpegtsPlayerImpl,
  type MediaInfo,
  type MpegtsPlayerProps,
  type MpegtsPlayerRef,
  type PlayerStatus,
  type StatisticsInfo,
} from 'mpegts-react'

const DEFAULT_URL = import.meta.env.VITE_DEMO_URL || ''

// ponytail: bridge a @types/react version gap — the lib's built .d.ts is
// emitted with @types/react@18 (forwardRef render returns ReactNode), while
// this app pins @types/react@17 (JSX needs ReactElement | null), so the raw
// import throws TS2786. Recast it to the React-17-typed forwardRef result;
// same component at runtime, only the static type is adjusted. Fix at the
// type-source (align @types/react across lib/app) is out of this file's scope.
const MpegtsPlayer = MpegtsPlayerImpl as unknown as React.ForwardRefExoticComponent<
  React.PropsWithoutRef<MpegtsPlayerProps> & React.RefAttributes<MpegtsPlayerRef>
>
const STORAGE_KEY = 'mpegts_demo_url'

type GridLayout = 1 | 4 | 9

const STATUS_COLORS: Record<PlayerStatus, string> = {
  connecting: 'text-yellow-500',
  reconnecting: 'text-yellow-500',
  error: 'text-red-500',
  nosignal: 'text-gray-400',
  playing: 'text-green-500',
  stopped: 'text-gray-400',
}

// ponytail: lower = worse. Worst-of aggregate = lowest severity across tiles.
// Format mpegts.js speed (KB/s float) — integer KB/s, auto MB/s past 1024.
function fmtSpeed(kbps?: number): string {
  if (kbps == null || kbps < 0 || Number.isNaN(kbps)) return '0 KB/s'
  return kbps < 1024 ? `${Math.round(kbps)} KB/s` : `${(kbps / 1024).toFixed(1)} MB/s`
}

// Friendly codec names from mpegts.js MediaInfo.videoCodec codec IDs.
function fmtCodec(codec?: string): string {
  if (!codec) return '?'
  const c = codec.toLowerCase()
  if (c.startsWith('avc1')) return 'H.264'
  if (c.startsWith('hev1') || c.startsWith('hvc1')) return 'H.265'
  if (c.startsWith('av01')) return 'AV1'
  if (c.startsWith('vp09')) return 'VP9'
  return codec
}

// Short loader tag from StatisticsInfo.loaderType (e.g. 'websocket-loader' → 'ws').
function fmtLoader(lt?: string): string {
  if (!lt) return ''
  if (lt.includes('websocket')) return 'ws'
  if (lt.includes('fetch')) return 'fetch'
  if (lt.includes('xhr')) return 'xhr'
  return lt
}

const SEVERITY: Record<PlayerStatus, number> = {
  error: 0,
  reconnecting: 1,
  connecting: 2,
  playing: 3,
  stopped: 4,
  nosignal: 5,
}

const GRID_COLS: Record<GridLayout, string> = {
  1: 'grid-cols-1',
  4: 'grid-cols-2',
  9: 'grid-cols-3',
}

function worstOf(statuses: Record<number, PlayerStatus>, count: number): PlayerStatus {
  let worst: PlayerStatus = 'nosignal'
  let rank = SEVERITY.nosignal
  for (let i = 0; i < count; i++) {
    const s = statuses[i]
    if (s && SEVERITY[s] < rank) {
      worst = s
      rank = SEVERITY[s]
    }
  }
  return worst
}

export default function App() {
  const [url, setUrl] = useState(() => localStorage.getItem(STORAGE_KEY) || DEFAULT_URL)
  const [inputUrl, setInputUrl] = useState(url)
  const [muted, setMuted] = useState(true)
  const [gridLayout, setGridLayout] = useState<GridLayout>(1)
  const [enableWorker, setEnableWorker] = useState(true)
  const [statuses, setStatuses] = useState<Record<number, PlayerStatus>>({})
  const [stats, setStats] = useState<Record<number, StatisticsInfo>>({})
  const [mediaInfos, setMediaInfos] = useState<Record<number, MediaInfo>>({})

  const playerRefs = useRef<Record<number, MpegtsPlayerRef>>({})

  useEffect(() => {
    if (url) localStorage.setItem(STORAGE_KEY, url)
    else localStorage.removeItem(STORAGE_KEY)
  }, [url])

  // ponytail: fresh object each render is fine — the lib collapses `config`
  // via JSON.stringify in its sourceSignature, so a rebuild only fires when
  // enableWorker actually flips, not every render.
  const config = { enableWorker }
  const aggregateStatus = worstOf(statuses, gridLayout)

  const applyUrl = useCallback(() => {
    const trimmed = inputUrl.trim()
    setUrl(trimmed)
    setInputUrl(trimmed)
  }, [inputUrl])

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter') applyUrl()
    },
    [applyUrl],
  )

  const setPlayerRef = useCallback((i: number, el: MpegtsPlayerRef | null) => {
    if (el) playerRefs.current[i] = el
    else delete playerRefs.current[i]
  }, [])

  const reloadAll = useCallback(() => {
    for (const r of Object.values(playerRefs.current)) r?.reload()
  }, [])

  const playAll = useCallback(() => {
    for (const r of Object.values(playerRefs.current)) r?.play()
  }, [])

  const pauseAll = useCallback(() => {
    for (const r of Object.values(playerRefs.current)) r?.pause()
  }, [])

  return (
    <div className="min-h-screen bg-gray-950 text-white p-6">
      <div className="mx-auto max-w-[1800px] flex flex-col gap-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <svg
              className="size-6 text-blue-500"
              fill="none"
              stroke="currentColor"
              strokeWidth={1.5}
              viewBox="0 0 24 24"
            >
              <path
                d="m15.75 10.5 4.72-4.72a.75.75 0 0 1 1.28.53v11.38a.75.75 0 0 1-1.28.53l-4.72-4.72M4.5 18.75h9a2.25 2.25 0 0 0 2.25-2.25v-9a2.25 2.25 0 0 0-2.25-2.25h-9A2.25 2.25 0 0 0 2.25 7.5v9a2.25 2.25 0 0 0 2.25 2.25Z"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
            <h2 className="m-0 text-lg font-semibold">mpegts-react Demo</h2>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-gray-400">Status:</span>
            <span className={`text-sm font-medium ${STATUS_COLORS[aggregateStatus]}`}>
              {aggregateStatus}
            </span>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-6 xl:grid-cols-4">
          <div className="xl:col-span-3">
            <div className="mb-3 flex flex-wrap items-center gap-2">
              <span className="text-xs text-gray-400">Views:</span>
              {([1, 4, 9] as GridLayout[]).map((g) => (
                <button
                  key={g}
                  className={`rounded border px-2 py-1 text-xs transition-colors ${
                    gridLayout === g
                      ? 'border-blue-500 bg-blue-500/10 text-blue-500'
                      : 'border-gray-700 hover:border-blue-500 hover:text-blue-500'
                  }`}
                  onClick={() => setGridLayout(g)}
                >
                  {g}
                </button>
              ))}
              <div className="ml-auto flex gap-2">
                <button
                  className="rounded border border-gray-700 px-3 py-1 text-xs hover:bg-gray-800"
                  onClick={reloadAll}
                >
                  Reload
                </button>
                <button
                  className="rounded border border-gray-700 px-3 py-1 text-xs hover:bg-gray-800"
                  onClick={playAll}
                >
                  Play
                </button>
                <button
                  className="rounded border border-gray-700 px-3 py-1 text-xs hover:bg-gray-800"
                  onClick={pauseAll}
                >
                  Pause
                </button>
              </div>
            </div>

            <div className={`grid w-full gap-2 ${GRID_COLS[gridLayout]}`}>
              {Array.from({ length: gridLayout }, (_, i) => {
                const mi = mediaInfos[i]
                const st = stats[i]
                return (
                  <div
                    key={i}
                    className="relative aspect-video border border-gray-700 bg-black shadow-sm"
                  >
                    <MpegtsPlayer
                      ref={(el) => setPlayerRef(i, el)}
                      url={url}
                      muted={muted}
                      config={config}
                      onStatus={(s) => setStatuses((p) => ({ ...p, [i]: s }))}
                      onStatistics={(info) => setStats((p) => ({ ...p, [i]: info }))}
                      onMediaInfo={(info) => setMediaInfos((p) => ({ ...p, [i]: info }))}
                    />
                    {mi?.height && (
                      <span className="absolute right-1.5 top-1.5 rounded bg-black/60 px-1.5 py-0.5 font-mono text-[10px] text-emerald-300">
                        {mi.width ?? '?'}×{mi.height} ·{' '}
                        {mi.fps != null ? `${mi.fps} fps` : '? fps'} · {fmtCodec(mi.videoCodec)}
                      </span>
                    )}
                    {st && (
                      <span className="absolute bottom-1.5 left-1.5 rounded bg-black/60 px-1.5 py-0.5 font-mono text-[10px] text-gray-200">
                        {st.speed != null ? `↓ ${fmtSpeed(st.speed)} · ` : ''}
                        {st.decodedFrames != null ? `${st.decodedFrames}f · ` : ''}
                        drop {st.droppedFrames ?? 0}
                        {st.loaderType ? ` · ${fmtLoader(st.loaderType)}` : ''}
                      </span>
                    )}
                  </div>
                )
              })}
            </div>
          </div>

          <div className="flex flex-col gap-4">
            <div className="rounded-lg border border-gray-700 bg-gray-900 p-4">
              <h3 className="m-0 mb-3 text-sm font-semibold">Stream URL</h3>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={inputUrl}
                  onChange={(e) => setInputUrl(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="ws://host:port/live/stream.flv"
                  className="flex-1 rounded border border-gray-600 bg-gray-800 px-3 py-1.5 text-xs text-white outline-none focus:border-blue-500"
                />
                <button
                  className="rounded bg-blue-600 px-3 py-1.5 text-xs text-white hover:bg-blue-700"
                  onClick={applyUrl}
                >
                  Apply
                </button>
              </div>
              {!url && (
                <p className="mt-3 text-xs text-gray-500">
                  Enter a stream URL to begin. Empty URL shows No Signal.
                </p>
              )}
            </div>

            <div className="rounded-lg border border-gray-700 bg-gray-900 p-4">
              <h3 className="m-0 mb-3 text-sm font-semibold">Playback</h3>
              <div className="flex flex-col gap-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs text-gray-400">Muted</span>
                  <button
                    className={`rounded border px-3 py-1 text-xs transition-colors ${
                      muted
                        ? 'border-blue-500 bg-blue-500/10 text-blue-500'
                        : 'border-gray-700 hover:border-blue-500'
                    }`}
                    onClick={() => setMuted((v) => !v)}
                  >
                    {muted ? 'ON' : 'OFF'}
                  </button>
                </div>
                <div className="flex items-center justify-between">
                  <label htmlFor="enableWorker" className="text-xs text-gray-400">
                    enableWorker
                  </label>
                  <button
                    id="enableWorker"
                    className={`rounded border px-3 py-1 text-xs transition-colors ${
                      enableWorker
                        ? 'border-blue-500 bg-blue-500/10 text-blue-500'
                        : 'border-gray-700 hover:border-blue-500'
                    }`}
                    onClick={() => setEnableWorker((v) => !v)}
                    aria-pressed={enableWorker}
                  >
                    {enableWorker ? 'ON' : 'OFF'}
                  </button>
                </div>
                <div className="flex gap-2">
                  <button
                    className="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                    onClick={playAll}
                  >
                    Play
                  </button>
                  <button
                    className="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                    onClick={pauseAll}
                  >
                    Pause
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// apps/demo/src/App.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue';

import { Languages, Monitor } from 'lucide-vue-next';

import { Input, Slider, Switch } from 'antdv-next';

import { MpegtsPlayer } from 'mpegts-vue3';
import type { MediaInfo, MpegtsConfig, PlayerStatus, StatisticsInfo } from 'mpegts-vue3';

import { t, toggleLocale, useLocale } from './i18n';

type GridLayout = 1 | 4 | 9;

const lang = useLocale();
const langLabel = computed(() => (lang.value === 'en' ? '中文' : 'EN'));

const DEFAULT_URL = import.meta.env.VITE_DEMO_URL || '';
const STORAGE_KEY = 'mpegts_demo_url';

const gridLayout = ref<GridLayout>(1);
const muted = ref(true);
const inputUrl = ref(localStorage.getItem(STORAGE_KEY) || DEFAULT_URL);

watch(inputUrl, (v) => {
  v ? localStorage.setItem(STORAGE_KEY, v) : localStorage.removeItem(STORAGE_KEY);
});

const gridSlots = computed(() => {
  return Array.from({ length: gridLayout.value }, (_, i) => ({
    id: i,
  }));
});

const playerRefs = ref<Record<number, InstanceType<typeof MpegtsPlayer>>>({});
const playerStatuses = ref<Record<number, PlayerStatus>>({});
const playerStats = ref<Record<number, StatisticsInfo>>({});
const playerMediaInfo = ref<Record<number, MediaInfo>>({});

// Format mpegts.js speed (KB/s float) — integer KB/s, auto MB/s past 1024.
function fmtSpeed(kbps?: number): string {
  if (kbps == null || kbps < 0 || Number.isNaN(kbps)) return '0 KB/s';
  return kbps < 1024 ? `${Math.round(kbps)} KB/s` : `${(kbps / 1024).toFixed(1)} MB/s`;
}

// Friendly codec names: avc1→H.264, hev1/hvc1→H.265, av01→AV1, vp09→VP9.
function fmtCodec(codec?: string): string {
  if (!codec) return '?';
  const c = codec.toLowerCase();
  if (c.startsWith('avc1')) return 'H.264';
  if (c.startsWith('hev1') || c.startsWith('hvc1')) return 'H.265';
  if (c.startsWith('av01')) return 'AV1';
  if (c.startsWith('vp09')) return 'VP9';
  return codec;
}

// Short loader tag: websocket-loader→ws, fetch-stream-loader→fetch, xhr-loader→xhr.
function fmtLoader(lt?: string): string {
  if (!lt) return '';
  if (lt.includes('websocket')) return 'ws';
  if (lt.includes('fetch')) return 'fetch';
  if (lt.includes('xhr')) return 'xhr';
  return lt;
}

const activePlayerStatus = computed<PlayerStatus>(() => {
  const statuses = Object.values(playerStatuses.value);
  if (statuses.length === 0) return 'nosignal';
  if (statuses.includes('error')) return 'error';
  if (statuses.includes('reconnecting')) return 'reconnecting';
  if (statuses.includes('connecting')) return 'connecting';
  if (statuses.includes('playing')) return 'playing';
  return 'nosignal';
});

const statusColor = computed(() => {
  const map: Record<PlayerStatus, string> = {
    connecting: 'text-yellow-500',
    reconnecting: 'text-amber-500',
    error: 'text-red-500',
    nosignal: 'text-gray-400',
    playing: 'text-green-500',
    stopped: 'text-gray-400',
  };
  return map[activePlayerStatus.value];
});

const statusText = computed(() => {
  const key = activePlayerStatus.value as string
  return t(key)
});

const config: MpegtsConfig = reactive({
  enableWorker: true,
  enableStashBuffer: false,
  stashInitialSize: 384,
  liveBufferLatencyChasing: true,
  liveBufferLatencyChasingOnPaused: true,
  liveBufferLatencyMaxLatency: 1.5,
  liveBufferLatencyMinRemain: 0.3,
  liveSync: true,
  liveSyncMaxLatency: 1.2,
  liveSyncTargetLatency: 0.5,
  autoCleanupSourceBuffer: true,
  autoCleanupMaxBackwardDuration: 30,
  autoCleanupMinBackwardDuration: 10,
  fixAudioTimestampGap: true,
});

function applyUrl() {
  inputUrl.value = inputUrl.value.trim();
}

function onPlayerStatus(index: number, s: PlayerStatus) {
  playerStatuses.value[index] = s;
}

function onStatistics(index: number, info: StatisticsInfo) {
  // console.log('statistics:', info);
  playerStats.value[index] = info;
}

function onMediaInfo(index: number, info: MediaInfo) {
  // console.log('media info:', info); 
  playerMediaInfo.value[index] = info;
}

function playAll() {
  for (const r of Object.values(playerRefs.value)) {
    r?.play();
  }
}

function pauseAll() {
  for (const r of Object.values(playerRefs.value)) {
    r?.pause();
  }
}

function reloadAll() {
  for (const r of Object.values(playerRefs.value)) {
    r?.reload();
  }
}

function setPlayerRef(
  index: number,
  el: InstanceType<typeof MpegtsPlayer> | null,
) {
  if (el) {
    playerRefs.value[index] = el;
  } else {
    delete playerRefs.value[index];
  }
}

const gridColsClass = computed(() => {
  if (gridLayout.value === 9) return 'grid-cols-3';
  if (gridLayout.value === 4) return 'grid-cols-2';
  return 'grid-cols-1';
});
</script>

<template>
  <div class="min-h-screen bg-gray-950 text-white p-6">
    <div class="mx-auto max-w-[1800px] flex flex-col gap-6">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <Monitor class="size-6 text-blue-500" />
          <h2 class="m-0 text-lg font-semibold">{{ t('title') }}</h2>
        </div>
        <div class="flex items-center gap-4">
          <div class="flex items-center gap-2">
            <span class="text-xs text-gray-400">{{ t('status') }}:</span>
            <span class="text-sm font-medium" :class="statusColor">
              {{ statusText }}
            </span>
          </div>
          <button
            class="flex items-center gap-1 rounded border border-gray-700 px-2 py-1 text-xs transition-colors hover:border-blue-500 hover:text-blue-500"
            @click="toggleLocale"
          >
            <Languages class="size-3.5" />
            {{ langLabel }}
          </button>
        </div>
      </div>

      <div class="flex flex-col gap-6 xl:flex-row">
        <div class="min-w-0 xl:flex-1">
          <div class="mb-3 flex items-center gap-2">
            <span class="text-xs text-gray-400">{{ t('windows') }}:</span>
            <button
              v-for="layout in [1, 4, 9] as GridLayout[]"
              :key="layout"
              class="rounded border px-2 py-1 text-xs transition-colors"
              :class="
                gridLayout === layout
                  ? 'border-blue-500 bg-blue-500/10 text-blue-500'
                  : 'border-gray-700 hover:border-blue-500 hover:text-blue-500'
              "
              @click="gridLayout = layout"
            >
              {{ layout }} {{ layout === 1 ? t('window') : t('windows') }}
            </button>
            <div class="ml-auto flex gap-2">
              <button
                class="rounded border border-gray-700 px-3 py-1 text-xs hover:bg-gray-800"
                @click="playAll"
              >
                {{ t('playAll') }}
              </button>
              <button
                class="rounded border border-gray-700 px-3 py-1 text-xs hover:bg-gray-800"
                @click="pauseAll"
              >
                {{ t('pauseAll') }}
              </button>
            </div>
          </div>

          <div
            v-if="gridLayout === 1"
            class="relative aspect-video w-full overflow-hidden rounded-lg border border-gray-700 bg-black shadow-sm"
          >
            <MpegtsPlayer
              :ref="(el: any) => setPlayerRef(0, el)"
              :url="inputUrl"
              :muted="muted"
              :config="config"
              @status="(s: PlayerStatus) => onPlayerStatus(0, s)"
              @statistics="(info: StatisticsInfo) => onStatistics(0, info)"
              @mediaInfo="(info: MediaInfo) => onMediaInfo(0, info)"
            />
            <div
              v-if="playerMediaInfo[0]?.height"
              class="pointer-events-none absolute right-1.5 top-1.5 rounded bg-black/60 px-1.5 py-0.5 text-[10px] font-mono text-emerald-300"
            >
                {{ playerMediaInfo[0].width }}×{{ playerMediaInfo[0].height }} · {{ playerMediaInfo[0].fps }} fps · {{ fmtCodec(playerMediaInfo[0].videoCodec) }}
            </div>
            <div
              v-if="playerStats[0]"
              class="pointer-events-none absolute bottom-1.5 left-1.5 rounded bg-black/60 px-1.5 py-0.5 text-[10px] font-mono text-gray-200"
            >
              ↓ {{ fmtSpeed(playerStats[0].speed) }} · {{ playerStats[0].decodedFrames ?? 0 }}f · drop {{ playerStats[0].droppedFrames ?? 0 }}<span v-if="playerStats[0].loaderType"> · {{ fmtLoader(playerStats[0].loaderType) }}</span>
            </div>
          </div>

          <div v-else class="grid w-full gap-2" :class="gridColsClass">
            <div
              v-for="slot in gridSlots"
              :key="slot.id"
              class="relative aspect-video w-full overflow-hidden rounded-lg border border-gray-700 bg-black shadow-sm"
            >
              <MpegtsPlayer
                :ref="(el: any) => setPlayerRef(slot.id, el)"
                :url="inputUrl"
                :muted="muted"
                :config="config"
                @status="(s: PlayerStatus) => onPlayerStatus(slot.id, s)"
                @statistics="(info: StatisticsInfo) => onStatistics(slot.id, info)"
                @mediaInfo="(info: MediaInfo) => onMediaInfo(slot.id, info)"
              />
              <div
                v-if="playerMediaInfo[slot.id]?.height"
                class="pointer-events-none absolute right-1.5 top-1.5 rounded bg-black/60 px-1.5 py-0.5 text-[10px] font-mono text-emerald-300"
              >
                {{ playerMediaInfo[slot.id].width }}×{{ playerMediaInfo[slot.id].height }} · {{ playerMediaInfo[slot.id].fps }} fps · {{ fmtCodec(playerMediaInfo[slot.id].videoCodec) }}
              </div>
              <div
                v-if="playerStats[slot.id]"
                class="pointer-events-none absolute bottom-1.5 left-1.5 rounded bg-black/60 px-1.5 py-0.5 text-[10px] font-mono text-gray-200"
              >
                ↓ {{ fmtSpeed(playerStats[slot.id].speed) }} · {{ playerStats[slot.id].decodedFrames ?? 0 }}f · drop {{ playerStats[slot.id].droppedFrames ?? 0 }}<span v-if="playerStats[slot.id].loaderType"> · {{ fmtLoader(playerStats[slot.id].loaderType) }}</span>
              </div>
            </div>
          </div>
        </div>

        <div class="flex flex-col gap-4 xl:w-80 xl:shrink-0">
          <div class="rounded-lg border border-gray-700 bg-gray-900 p-4">
            <h3 class="m-0 mb-3 text-sm font-semibold">{{ t('streamUrl') }}</h3>
            <div class="flex gap-2">
              <Input
                v-model:value="inputUrl"
                placeholder="ws://host:port/live/stream.flv"
                class="flex-1"
                size="small"
                @press-enter="applyUrl"
              />
              <button
                class="rounded bg-blue-600 px-3 py-1 text-xs text-white hover:bg-blue-700"
                @click="applyUrl"
              >
                {{ t('apply') }}
              </button>
            </div>
          </div>

          <div class="rounded-lg border border-gray-700 bg-gray-900 p-4">
            <h3 class="m-0 mb-3 text-sm font-semibold">{{ t('playbackControl') }}</h3>
            <div class="flex flex-col gap-3">
              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">{{ t('muted') }}</span>
                <Switch v-model:checked="muted" size="small" />
              </div>
              <div class="flex gap-2">
                <button
                  class="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                  @click="playAll"
                >
                  {{ t('play') }}
                </button>
                <button
                  class="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                  @click="pauseAll"
                >
                  {{ t('pause') }}
                </button>
                <button
                  class="flex-1 rounded border border-gray-700 px-3 py-1.5 text-xs hover:bg-gray-800"
                  @click="reloadAll"
                >
                  {{ t('reload') }}
                </button>
              </div>
            </div>
          </div>

          <div class="rounded-lg border border-gray-700 bg-gray-900 p-4">
            <h3 class="m-0 mb-3 text-sm font-semibold">{{ t('liveParameters') }}</h3>
            <div class="flex flex-col gap-3">
              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('enableWorker') }}
                </span>
                <Switch v-model:checked="config.enableWorker" size="small" />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('enableStashBuffer') }}
                </span>
                <Switch
                  v-model:checked="config.enableStashBuffer"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('stashInitialSize') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.stashInitialSize }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.stashInitialSize"
                  :min="64"
                  :max="2048"
                  :step="64"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('latencyChasing') }}
                </span>
                <Switch
                  v-model:checked="config.liveBufferLatencyChasing"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('chaseOnPause') }}
                </span>
                <Switch
                  v-model:checked="config.liveBufferLatencyChasingOnPaused"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('maxLatency') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.liveBufferLatencyMaxLatency }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.liveBufferLatencyMaxLatency"
                  :min="0.5"
                  :max="10"
                  :step="0.1"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('minRemain') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.liveBufferLatencyMinRemain }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.liveBufferLatencyMinRemain"
                  :min="0.1"
                  :max="5"
                  :step="0.1"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('rateSync') }}
                </span>
                <Switch v-model:checked="config.liveSync" size="small" />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('syncMaxLatency') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.liveSyncMaxLatency }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.liveSyncMaxLatency"
                  :min="0.5"
                  :max="10"
                  :step="0.1"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('syncTargetLatency') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.liveSyncTargetLatency }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.liveSyncTargetLatency"
                  :min="0.1"
                  :max="5"
                  :step="0.1"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('autoCleanup') }}
                </span>
                <Switch
                  v-model:checked="config.autoCleanupSourceBuffer"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('cleanupMaxBackward') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.autoCleanupMaxBackwardDuration }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.autoCleanupMaxBackwardDuration"
                  :min="5"
                  :max="300"
                  :step="5"
                  size="small"
                />
              </div>

              <div>
                <div class="mb-1 flex items-center justify-between">
                  <span class="text-xs text-gray-400">
                    {{ t('cleanupMinBackward') }}
                  </span>
                  <span class="text-xs font-mono text-blue-400">
                    {{ config.autoCleanupMinBackwardDuration }}
                  </span>
                </div>
                <Slider
                  v-model:value="config.autoCleanupMinBackwardDuration"
                  :min="5"
                  :max="120"
                  :step="5"
                  size="small"
                />
              </div>

              <div class="flex items-center justify-between">
                <span class="text-xs text-gray-400">
                  {{ t('fixAudioTimestampGap') }}
                </span>
                <Switch
                  v-model:checked="config.fixAudioTimestampGap"
                  size="small"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
